from typing import Union, Generator, Optional, Any, Tuple, Dict
import numpy as np
from numpy.typing import NDArray

class Error:
    OK: int
    ERROR_NO_SUCH_FILE: int
    ERROR_COEFFICIENT_OUT_OF_IMAGE_BOUNDS: int
    ERROR_CHECKSUM_MISMATCH: int
    ERROR_CTB_OUTSIDE_IMAGE_AREA: int
    ERROR_OUT_OF_MEMORY: int
    ERROR_CODED_PARAMETER_OUT_OF_RANGE: int
    ERROR_IMAGE_BUFFER_FULL: int
    ERROR_CANNOT_START_THREADPOOL: int
    ERROR_LIBRARY_INITIALIZATION_FAILED: int
    ERROR_LIBRARY_NOT_INITIALIZED: int
    ERROR_WAITING_FOR_INPUT_DATA: int
    ERROR_CANNOT_PROCESS_SEI: int
    ERROR_PARAMETER_PARSING: int
    ERROR_NO_INITIAL_SLICE_HEADER: int
    ERROR_PREMATURE_END_OF_SLICE: int
    ERROR_UNSPECIFIED_DECODING_ERROR: int
    ERROR_NOT_IMPLEMENTED_YET: int
    WARNING_NO_WPP_CANNOT_USE_MULTITHREADING: int
    WARNING_WARNING_BUFFER_FULL: int
    WARNING_PREMATURE_END_OF_SLICE_SEGMENT: int
    WARNING_INCORRECT_ENTRY_POINT_OFFSET: int
    WARNING_CTB_OUTSIDE_IMAGE_AREA: int

class ChromaFormat:
    CHROMA_MONO: int
    CHROMA_420: int
    CHROMA_422: int
    CHROMA_444: int

class Parameter:
    PARAM_BOOL_SEI_CHECK_HASH: int
    PARAM_DUMP_SPS_HEADERS: int
    PARAM_DUMP_VPS_HEADERS: int
    PARAM_DUMP_PPS_HEADERS: int
    PARAM_DUMP_SLICE_HEADERS: int
    PARAM_ACCELERATION_CODE: int
    PARAM_SUPPRESS_FAULTY_PICTURES: int
    PARAM_DISABLE_DEBLOCKING: int
    PARAM_DISABLE_SAO: int

def get_version() -> str: ...
def get_error_text(err_number: int) -> str: ...
def isOk(err_number: int) -> bool: ...
def set_verbosity(level: int) -> None: ...

class Image:
    @property
    def pts(self) -> int: ...
    @property
    def chroma_format(self) -> int: ...
    def width(self, channel: int = 0) -> int: ...
    def height(self, channel: int = 0) -> int: ...
    def get_bits_per_pixel(self, channel: int = 0) -> int: ...
    def plane(self, channel: int) -> NDArray[Any]: ...
    def yuv(self) -> Tuple[NDArray[Any], Optional[NDArray[Any]], Optional[NDArray[Any]]]: ...
    def nal_header(self) -> Dict[str, Any]: ...
    @property
    def full_range(self) -> int: ...
    @property
    def colour_primaries(self) -> int: ...
    @property
    def transfer_characteristics(self) -> int: ...
    @property
    def matrix_coefficients(self) -> int: ...
    def to_rgb(self) -> NDArray[np.uint8]: ...
    def get_image_ptr(self) -> Any: ...

class decoder:
    def __init__(self, threads: int = 0) -> None: ...
    def push_data(self, data: bytes, pts: int = 0) -> None: ...
    def push_end_of_NAL(self) -> None: ...
    def push_end_of_frame(self) -> None: ...
    def flush(self) -> None: ...
    def decode(self) -> Generator[Image, None, None]: ...
    def load_file(self, path: str, buffer_size: int = 1048576) -> Generator[Image, None, None]: ...
    def reset(self) -> None: ...
    def get_number_of_input_bytes_pending(self) -> int: ...
    @property
    def highest_tid(self) -> int: ...
    @property
    def current_tid(self) -> int: ...
    def set_limit_tid(self, tid: int) -> None: ...
    def set_parameter(self, param: int, value: Union[bool, int]) -> None: ...
    def get_parameter(self, param: int) -> bool: ...

class FileDemuxer:
    def __init__(self, filename: str) -> None: ...
    def get_headers(self) -> bytes: ...
    def get_fps(self) -> float: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> 'FileDemuxer': ...
    def __next__(self) -> bytes: ...
    def __next__(self) -> bytes: ...
