from typing import Any
import numpy as np
from numpy.typing import NDArray

def draw_CB_grid(img_cap: Any, dst: NDArray[np.uint8], value: int, pixelSize: int) -> None: ...
def draw_TB_grid(img_cap: Any, dst: NDArray[np.uint8], value: int, pixelSize: int) -> None: ...
def draw_PB_grid(img_cap: Any, dst: NDArray[np.uint8], value: int, pixelSize: int) -> None: ...
def draw_PB_pred_modes(img_cap: Any, dst: NDArray[np.uint8], pixelSize: int) -> None: ...
def draw_intra_pred_modes(img_cap: Any, dst: NDArray[np.uint8], value: int, pixelSize: int) -> None: ...
def draw_QuantPY(img_cap: Any, dst: NDArray[np.uint8], pixelSize: int) -> None: ...
def draw_Motion(img_cap: Any, dst: NDArray[np.uint8], pixelSize: int) -> None: ...
def draw_Slices(img_cap: Any, dst: NDArray[np.uint8], pixelSize: int) -> None: ...
def draw_Tiles(img_cap: Any, dst: NDArray[np.uint8], pixelSize: int) -> None: ...
