from typing import Union

def get_version() -> str: ...
def get_error_text(err_number: int) -> str: ...
def isOk(err_number: int) -> bool: ...
def set_verbosity(level: int) -> None: ...

class decoder:
    w: int
    h: int
    chroma: int
    bps: int
    pts: int
    matrix_coeff: int

    wC: int
    hC: int

    def __init__(self, threads: int, buffer_size: int) -> None: ...
    def load(self, vedio_path: str) -> int: ...
    def decode(self) -> None: ...
    def free_image(self) -> None: ...
    def get_highest_TID(self) -> int: ...
    def get_current_TID(self) -> int: ...
    def set_limit_TID(self, ttd: int): ...
    def set_framerate_ratio(self, percent: int): ...
    def change_framerate(self, more_vs_less: int) -> int: ...
    def set_parameter(self, param: int, value: Union[int, bool]): ...
    def get_parameter(self, param: int) -> bool: ...
