def get_version() -> str: ...

class decoder:
    def __init__(self, threads: int, buffer_size: int) -> None: ...
    def load(self, data) -> int: ...
    def decode_frame(self) -> None | int: ...
    def decode(self) -> None: ...
    def free_image(self) -> None: ...
