def get_version()->str:...

class decode_decoder():
    def __init__(self,threads:int) -> None: ...
    def load(self,data)->int:...
    def decode_frame(self)-> None|int :...            
    def decode(self)->None:...        
    def free_image(self)->None:...
    def stop(self)->None:...
    def get_PTS(self)->None:...
